import Head from "next/head";
import Navbar from "../components/Navbar";
import Table from "../components/Table";
import Popup from "../components/UI/Popup";

export default function Home() {
  return (
    <>
      <Head>
        <title>Admin Portal</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="min-h-screen">
        <Navbar />
        <div className="py-8 px-20 flex flex-col items-start justify-center">
          <div className="w-full flex justify-between items-center">
            <h2 className="font-semibold text-xl">Camapaign Management Console</h2>
            <Popup />
          </div>
          <div className="pt-6 w-full">
            <Table />
          </div>
        </div>
      </div>
    </>
  );
}
