const tableData = [
  {
    name: "Flight Booking: AUH - SIN",
    category: "Miles",
    amount: 12180,
    type: "Redeem",
    date: "11 Feb 2022",
  },
  {
    name: "Hotel Booking: One Pacific Place",
    category: "Points",
    amount: 2230,
    type: "Redeem",
    date: "04 Jan 2022",
  },
  {
    name: "Hotel Booking: Resort World Sentosa",
    category: "Points",
    amount: 26262,
    type: "Redeem",
    date: "02 Jan 2022",
  },
  {
    name: "Flight Booking: AUH - SYD",
    category: "Miles",
    amount: 28292,
    type: "Redeem",
    date: "01 Jan 2022",
  },
  {
    name: "Flight Booking: SYD - JFK",
    category: "Miles",
    amount: 2482,
    type: "Redeem",
    date: "22 Dec 2021",
  },
  {
    name: "Hotel Booking: Hotel 81 Dickson",
    category: "Points",
    amount: 5850,
    type: "Redeem",
    date: "20 Dec 2021",
  },
  {
    name: "Bath & Body Works Bonus",
    category: "Points",
    amount: 7583,
    type: "Earn",
    date: "13 Dec 2021",
  },
  {
    name: "Flight Booking: SYD - JFK",
    category: "Flight",
    amount: 2482,
    type: "Redeem",
    date: "22 Dec 2021",
  },
  {
    name: "Hotel Booking: Hotel 81 Dickson",
    category: "Hotel",
    amount: 5850,
    type: "Redeem",
    date: "20 Dec 2021",
  },
  {
    name: "Bath & Body Works Bonus",
    category: "Merchant",
    amount: 7583,
    type: "Earn",
    date: "13 Dec 2021",
  },
  {
    name: "Flight Booking: AUH - SIN",
    category: "Flight",
    amount: 12180,
    type: "Redeem",
    date: "11 Feb 2022",
  },
  {
    name: "Hotel Booking: One Pacific Place",
    category: "Hotel",
    amount: 2230,
    type: "Redeem",
    date: "04 Jan 2022",
  },
  {
    name: "Hotel Booking: Resort World Sentosa",
    category: "Hotel",
    amount: 26262,
    type: "Redeem",
    date: "02 Jan 2022",
  },
  {
    name: "Flight Booking: AUH - SIN",
    category: "Flight",
    amount: 12180,
    type: "Redeem",
    date: "11 Feb 2022",
  },
  {
    name: "Hotel Booking: One Pacific Place",
    category: "Hotel",
    amount: 2230,
    type: "Redeem",
    date: "04 Jan 2022",
  },
  {
    name: "Hotel Booking: Resort World Sentosa",
    category: "Hotel",
    amount: 26262,
    type: "Redeem",
    date: "02 Jan 2022",
  },
  {
    name: "Flight Booking: AUH - SYD",
    category: "Flight",
    amount: 28292,
    type: "Redeem",
    date: "01 Jan 2022",
  },
  {
    name: "Flight Booking: SYD - JFK",
    category: "Flight",
    amount: 2482,
    type: "Redeem",
    date: "22 Dec 2021",
  },
  {
    name: "Hotel Booking: Hotel 81 Dickson",
    category: "Hotel",
    amount: 5850,
    type: "Redeem",
    date: "20 Dec 2021",
  },
  {
    name: "Bath & Body Works Bonus",
    category: "Merchant",
    amount: 7583,
    type: "Earn",
    date: "13 Dec 2021",
  },
  {
    name: "Flight Booking: SYD - JFK",
    category: "Flight",
    amount: 2482,
    type: "Redeem",
    date: "22 Dec 2021",
  },
  {
    name: "Hotel Booking: Hotel 81 Dickson",
    category: "Hotel",
    amount: 5850,
    type: "Redeem",
    date: "20 Dec 2021",
  },
];

export default tableData;
